/* DINO QUEST — modular canvas runner built from the uploaded Dino Runner foundation. */
const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),$=id=>document.getElementById(id);
const ui={hud:$('hud'),start:$('startScreen'),pause:$('pauseScreen'),quiz:$('quizScreen'),over:$('gameOverScreen'),score:$('score'),best:$('highScore'),lives:$('lives'),level:$('level'),bar:$('progressBar'),toast:$('toast'),q:$('quizQuestion'),subject:$('quizSubject'),counter:$('quizCounter'),answers:$('answers'),feedback:$('quizFeedback')};
let W=1000,H=500,dpr=1,last=0,state='menu',paused=false,quizOpen=false,score=0,level=1,lives=3,gameSpeed=350,gameTime=0,obstacles=[],particles=[],powerups=[],spawnT=0,nextSpawn=1.1,passed=0,quizCount=0,questionIndex=0,quizDue=5,questionPool=[],audio=null,shake=0;
let best=+localStorage.getItem('dinoQuestBest')||0, leaderboard=JSON.parse(localStorage.getItem('dinoQuestLeaderboard')||'[]');
const GROUND=78,GRAV=2200,JUMP=-760;
const player={x:80,y:0,w:54,h:58,vy:0,grounded:true,reset(){this.x=Math.max(35,W*.08);this.y=H-GROUND-this.h;this.vy=0;this.grounded=true},jump(){if(state==='run'&&!quizOpen&&this.grounded){this.vy=JUMP;sound(520,.08,'square',.035);for(let i=0;i<5;i++)particle(this.x+22,this.y+54,'jump')}} ,update(dt){this.vy+=GRAV*dt;this.y+=this.vy*dt;const gy=H-GROUND-this.h;if(this.y>=gy){this.y=gy;this.vy=0;this.grounded=true}}};
function resize(){const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);player.reset()} addEventListener('resize',resize);resize();
function reset(){state='run';paused=false;quizOpen=false;score=0;level=1;lives=3;gameSpeed=350;gameTime=0;obstacles=[];particles=[];powerups=[];spawnT=0;nextSpawn=.9;passed=0;quizCount=0;quizDue=5;questionPool=[...QUESTION_BANK].sort(()=>Math.random()-.5);questionIndex=0;player.reset();hideAll();ui.hud.classList.remove('hidden');sound(330,.08);setTimeout(()=>sound(660,.1),80);updateHUD()}
function hideAll(){ui.start.classList.add('hidden');ui.pause.classList.add('hidden');ui.quiz.classList.add('hidden');ui.over.classList.add('hidden')}
function start(){reset()}
function togglePause(){if(state!=='run'||quizOpen)return;paused=!paused;ui.pause.classList.toggle('hidden',!paused)}
function spawnObstacle(){const p=Math.random(),type=p<.45?'small':p<.75?'tall':p<.92?'double':'bird';let o={x:W+30,type,passed:false};if(type==='small'){o.w=28;o.h=42+Math.random()*14}else if(type==='tall'){o.w=34;o.h=62+Math.random()*20}else if(type==='double'){o.w=70;o.h=42}else{o.w=46;o.h=30;o.y=H-GROUND-90-Math.random()*45}o.y??=H-GROUND-o.h;obstacles.push(o)}
function spawnPower(){powerups.push({x:W+30,y:H-GROUND-115-Math.random()*100,r:13,type:Math.random()<.5?'shield':'boost'})}
function updateObstacles(dt){spawnT+=dt;if(spawnT>=nextSpawn){spawnObstacle();spawnT=0;const min=Math.max(.72,1.28-gameSpeed/1700),max=Math.max(1.05,1.9-gameSpeed/1500);nextSpawn=min+Math.random()*(max-min);if(Math.random()<.12+level*.02)spawnPower()}for(let i=obstacles.length-1;i>=0;i--){let o=obstacles[i];o.x-=gameSpeed*dt;if(!o.passed&&o.x+o.w<player.x){o.passed=true;passed++;score+=10;for(let j=0;j<4;j++)particle(o.x,o.y,'score');if(passed>=quizDue){quizDue+=5;openQuiz()}}if(o.x+o.w<-60)obstacles.splice(i,1)}for(let i=powerups.length-1;i>=0;i--){let p=powerups[i];p.x-=gameSpeed*dt;p.spin=(p.spin||0)+dt*5;if(p.x<-40)powerups.splice(i,1);else if(circleRect(p,player)){powerups.splice(i,1);if(p.type==='shield'){lives=Math.min(3,lives+1);toast('🛡️ LIFE SHARD +1')}else{gameSpeed=Math.min(1000,gameSpeed+110);score+=50;toast('⚡ TURBO BOOST +50')}}}}
function circleRect(c,r){const x=Math.max(r.x,Math.min(c.x,r.x+r.w)),y=Math.max(r.y,Math.min(c.y,r.y+r.h));return Math.hypot(c.x-x,c.y-y)<c.r}
function hitbox(o){return{x:o.x+5,y:o.y+3,w:o.w-10,h:o.h-5}}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
let shield=0;
function collision(){const p={x:player.x+7,y:player.y+5,w:player.w-12,h:player.h-8};for(let i=obstacles.length-1;i>=0;i--){if(overlap(p,hitbox(obstacles[i]))){if(shield>0){shield=0;obstacles.splice(i,1);toast('🛡️ SHIELD SAVED YOU!');sound(760,.15,'triangle');for(let j=0;j<14;j++)particle(player.x+25,player.y+25,'shield');}else{lives--;shake=12;obstacles.splice(i,1);sound(150,.2,'sawtooth');toast(lives?'💥 Ouch! -1 life':'💀 Quest over');if(lives<=0)end();}return}}}
function openQuiz(){quizOpen=true;paused=false;ui.quiz.classList.remove('hidden');const q=questionPool[questionIndex++%questionPool.length];ui.subject.textContent=q.subject.toUpperCase();ui.counter.textContent='QUEST '+(quizCount+1);ui.q.textContent=q.q;ui.feedback.textContent='';ui.answers.innerHTML='';q.a.forEach((a,i)=>{const b=document.createElement('button');b.className='answer';b.textContent=String.fromCharCode(65+i)+'. '+a;b.onclick=()=>answer(b,i,q.c);ui.answers.appendChild(b)});sound(660,.1,'sine')}
function answer(btn,i,c){[...ui.answers.children].forEach(b=>b.disabled=true);if(i===c){btn.classList.add('correct');quizCount++;score+=100+level*20;level++;gameSpeed=Math.min(1000,gameSpeed+28);ui.feedback.textContent='✅ Correct! + bonus points — Stage unlocked!';sound(880,.12,'sine');for(let j=0;j<15;j++)particle(W/2,H/2,'win');setTimeout(closeQuiz,850)}else{btn.classList.add('wrong');lives--;ui.feedback.textContent=lives?'❌ Not quite. You lost a life.':'❌ Incorrect — no lives left.';sound(180,.2,'sawtooth');if(lives<=0)setTimeout(()=>{closeQuiz();end()},700);else setTimeout(closeQuiz,900)}}
function closeQuiz(){quizOpen=false;ui.quiz.classList.add('hidden');quizDue=Math.max(quizDue,passed+4)}
function end(){if(state!=='run')return;state='over';best=Math.max(best,Math.floor(score));localStorage.setItem('dinoQuestBest',best);leaderboard.push({score:Math.floor(score),level,at:Date.now()});leaderboard.sort((a,b)=>b.score-a.score);leaderboard=leaderboard.slice(0,5);localStorage.setItem('dinoQuestLeaderboard',JSON.stringify(leaderboard));ui.over.classList.remove('hidden');$('finalScore').textContent=Math.floor(score);$('finalBest').textContent=best;$('finalLevel').textContent=level;$('finalQuizzes').textContent=quizCount;renderBoard();sound(260,.15,'sawtooth');setTimeout(()=>sound(180,.25,'sawtooth'),120)}
function renderBoard(){const el=$('leaderboard');el.innerHTML='';leaderboard.forEach((x,i)=>{const li=document.createElement('li');li.innerHTML=`${i+1}. <b>${x.score}</b> — Level ${x.level}`;el.appendChild(li)})}
function updateHUD(){ui.score.textContent=String(Math.floor(score)).padStart(5,'0');ui.best.textContent=String(Math.max(best,Math.floor(score))).padStart(5,'0');ui.lives.textContent='♥'.repeat(lives)+'♡'.repeat(3-lives);ui.level.textContent=level;ui.bar.style.width=((passed%5)/5*100)+'%'}
function update(dt){if(state!=='run'||paused||quizOpen)return;dt=Math.min(dt,.035);gameTime+=dt;gameSpeed=Math.min(1000,gameSpeed+dt*(7+level*.7));score+=dt*(4+level*.4);player.update(dt);updateObstacles(dt);collision();if(Math.random()<dt*12)particle(Math.random()*W,H-GROUND-3,'dust');for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.g*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1)}if(shake>0)shake-=dt*40;updateHUD()}
function particle(x,y,type){const colors={jump:'#4de6ff',score:'#a7ff72',shield:'#7b7cff',win:'#ffd166',dust:'#71809b'};particles.push({x,y,vx:(Math.random()-.5)*90,vy:-30-Math.random()*120,g:180,life:.35+Math.random()*.4,size:2+Math.random()*4,c:colors[type]||'#fff'})}
function toast(t){ui.toast.textContent=t;ui.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>ui.toast.classList.remove('show'),1000)}
function draw(){ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBG();drawPowerups();obstacles.forEach(drawObstacle);drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*2);ctx.fillStyle=p.c;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.restore()}
let bgT=0;function drawBG(){bgT+=.01;const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0a1025');g.addColorStop(1,'#13213a');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<60;i++){const x=(i*173-bgT*20)%W,y=35+(i*71)%220;ctx.globalAlpha=.35;ctx.fillStyle=i%3?'#7b7cff':'#4de6ff';ctx.fillRect((x+W)%W,y,1.5,1.5)}ctx.globalAlpha=1;parallaxLayer(H-GROUND-120,.25,'#17284a',90);parallaxLayer(H-GROUND-70,.5,'#1c3150',65);ctx.fillStyle='#0b1425';ctx.fillRect(0,H-GROUND,W,GROUND);ctx.strokeStyle='#304968';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,H-GROUND);ctx.lineTo(W,H-GROUND);ctx.stroke();const off=(gameTime*gameSpeed)%48;for(let x=-off;x<W;x+=48){ctx.fillStyle='#263b59';ctx.fillRect(x,H-GROUND+18,22,3)}}function parallaxLayer(base,freq,col,amp){ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(0,H-GROUND);for(let x=0;x<=W;x+=40){const y=base-Math.sin(x*.012+gameTime*freq)*amp-Math.cos(x*.006)*20;ctx.lineTo(x,y)}ctx.lineTo(W,H-GROUND);ctx.closePath();ctx.fill()}
function drawPlayer(){const x=player.x,y=player.y;ctx.save();ctx.translate(x,y);ctx.fillStyle='#9df37a';ctx.shadowColor='#67e85f';ctx.shadowBlur=10;ctx.fillRect(8,19,33,28);ctx.fillRect(28,6,25,25);ctx.fillRect(46,16,12,11);ctx.fillRect(0,28,13,8);ctx.fillRect(14,44,8,14);ctx.fillRect(33,44,8,14);ctx.shadowBlur=0;ctx.fillStyle='#08111f';ctx.fillRect(46,11,4,4);ctx.fillStyle='#dfffe1';ctx.fillRect(45,10,3,3);ctx.restore()}
function drawObstacle(o){ctx.save();ctx.translate(o.x,o.y);if(o.type==='bird'){ctx.fillStyle='#ff5f9e';ctx.beginPath();ctx.ellipse(23,14,22,11,0,0,Math.PI*2);ctx.fill();ctx.fillRect(3,10,15,5);ctx.fillStyle='#0b1425';ctx.fillRect(31,10,3,3)}else{ctx.fillStyle=o.type==='tall'?'#ff6b6b':'#a7ff72';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=8;ctx.fillRect(o.w*.32,0,o.w*.34,o.h);ctx.fillRect(0,o.h*.38,o.w*.38,8);ctx.fillRect(o.w*.05,o.h*.2,8,o.h*.35);if(o.type!=='small'){ctx.fillRect(o.w*.62,o.h*.55,o.w*.38,8);ctx.fillRect(o.w*.82,o.h*.35,8,o.h*.35)}}ctx.restore()}
function drawPowerups(){powerups.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.spin||0);ctx.fillStyle=p.type==='shield'?'#7b7cff':'#ffd166';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#0a1020';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.type==='shield'?'♥':'⚡',0,1);ctx.restore()})}
function loop(t){const dt=last?(t-last)/1000:0;last=t;update(dt);draw();requestAnimationFrame(loop)}
function initAudio(){if(!audio){const C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C()}if(audio?.state==='suspended')audio.resume()}
function sound(freq,dur,type='square',vol=.025){if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
$('startBtn').onclick=()=>{initAudio();start()};$('restartBtn').onclick=()=>{initAudio();start()};$('menuBtn').onclick=()=>{state='menu';hideAll();ui.start.classList.remove('hidden')};$('pauseBtn').onclick=togglePause;$('resumeBtn').onclick=togglePause;$('quitBtn').onclick=()=>{state='menu';hideAll();ui.start.classList.remove('hidden')};
document.addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();initAudio();if(state==='menu')start();else if(state==='run')player.jump();else if(state==='over')start()}if(e.code==='KeyP')togglePause();if(e.code==='KeyR'&&state==='over')start()});canvas.addEventListener('pointerdown',e=>{e.preventDefault();initAudio();if(state==='menu')start();else if(state==='run')player.jump();else if(state==='over')start()});
player.reset();updateHUD();renderBoard();requestAnimationFrame(loop);
